name: carla
services:
  bridge:
    container_name: ros_bridge
    build:
      dockerfile: ./Dockerfile
      args:
        CARLA_VERSION: 0.9.13
        ROS_DISTRO: foxy
        ROS_DOMAIN_ID: 10
    command:
      - source /opt/carla-ros-bridge/install/setup.bash && source /opt/carla/setup.bash && exec ros2 launch carla_ackermann_control carla_ros_bridge_with_ackermann_control.launch.py
    network_mode: "host"
    ipc: "host"
